module.exports = {
    EMPTY_PLAYER_NAME: { message: 'Player name should not be empty', errCode: 'EMPTY_PLAYER_NAME' },
    EXCEEDED_PLAYER_NAME: { message: 'Player name cannot be more than 15 letters', errCode: 'EXCEEDED_PLAYER_NAME' },
    INVALID_PLAYER_TOKEN: { message: 'Invalid Player Token', errCode: 'INVALID_PLAYER_TOKEN' },
    SERVER_ERROR: { message: 'Server Error', errCode: 'SERVER_ERROR' },
    INVALID_ROOM_ID: { message: 'Invalid Room ID', errCode: 'INVALID_ROOM_ID' },
    ROOM_NOT_FOUND: { message: 'Room Not found', errCode: 'ROOM_NOT_FOUND' },
    PLAYER_NOT_FOUND_IN_ROOM: { message: 'Player not found in Room', errCode: 'PLAYER_NOT_FOUND_IN_ROOM' },
    PLAYER_FOUND_IN_ROOM: { message: 'Player already in Room', errCode: 'PLAYER_FOUND_IN_ROOM' },
    ROOM_IS_FULL: { message: 'Room is Full', errCode: 'ROOM_IS_FULL' },
    NOT_YOUR_MOVE: { message: 'This is not your move', errCode: 'NOT_YOUR_MOVE' },
    GAME_STATUS_IS_NOT_CREATED: { message: "Game status should be created", errCode: 'GAME_STATUS_IS_NOT_CREATED' },
    GAME_STATUS_IS_NOT_STARTED: { message: 'Game status should be started', errCode: 'GAME_STATUS_IS_NOT_STARTED' },
    GAME_STATUS_IS_NOT_ENDED: { message: 'Game status should be ended', errCode: 'GAME_STATUS_IS_NOT_ENDED' },
    NOT_AN_ADMIN: { message: 'You are not a admin', errCode: 'NOT_AN_ADMIN' },
    INVALID_CARD: { message: 'Chosencard is invalid', errCode: 'INVALID_CARD' },
    CHOSEN_CARD_NOT_PRESENT: { message: 'Chosen card not present in your deck', errCode: 'CHOSEN_CARD_NOT_PRESENT' },
    PLAYER_SPOOFING: { message: 'Spoofing not allowed', errCode: 'PLAYER_SPOOFING' },
    CANT_START_GAME: { message: 'Atleast 2 players needed to start a game', errCode: 'CANT_START_GAME' },
    NOT_SAME_NUMBERS: { message: 'Chosencards numbers are not same', errCode: 'NOT_SAME_NUMBERS' },
    PLAYER_ACTION_NOT_SUBMIT: { message: 'Your action should be submitting card', errCode: 'PLAYER_ACTION_NOT_SUBMIT' },
    PLAYER_ACTION_NOT_TAKE: { message: 'Your action should be taking card', errCode: 'PLAYER_ACTION_NOT_TAKE' },
    PLAYER_ACTION_NOT_DECIDE: { message: "You didn't taken card yet", errCode: 'PLAYER_ACTION_NOT_DECIDE' },
    INVALID_TAKE_FROM: { message: 'Invalid take from', errCode: 'INVALID_TAKE_FROM' },
}